#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.
xset -b
# Change your keymap:
xmodmap "$HOME/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
unclutter -idle 2 &
# wmnd &
~/.screenlayout/top.sh
# wmsmixer -w &
# idesk &
nm-applet &
#nitrogen --restore &
exec ~/fehbg &
dropbox start &
insync start &
nextcloud &
compton -b --config ~/.compton.conf &


# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/brian/.fluxbox/log"
